### ISSUE TITLE
only the first date in a range displays in the search results for MODS records

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/stanford-mods#134]
See SW-3808.

For https://searchworks.stanford.edu/catalog?utf8=✓&search_field=search&q=dr719vn5159,  the date 1848 shows in the title of a search result because "only the first date in a range displays in the search results for MODS records".

![Image](https://user-images.githubusercontent.com/111218/178014709-db509ab3-e827-4e2e-a51c-e819363a06b1.png)

Is there some reason this shouldn't show the whole range?

**Comment by thatbudakguy** [comment]
- [ ] check exhibits to make sure it's ready to receive ranges from `pub_year_display_str` too
