### ISSUE TITLE
reimplement imprint_display

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/stanford-mods#52]
It should be more in the spirit of the marc data population, from 264 or 260.  publisher, place, year ...

**Comment by ndushay** [comment]
we should be able to use mods_display code for imprint information.  See https://github.com/sul-dlss/mods_display/wiki/Using-mods_display-from-non-rails-app

**Comment by ndushay** [comment]
if there is no single string method avail in mods_display or in SW use of mods_display, @jvine says "the simplest structure for imprint is:     Edition. - Place : Publisher, Date    "

**Comment by ndushay** [comment]
current (ick:  0700 for Papyri;  -17 for Roman coins) 

![papyri dates before](https://cloud.githubusercontent.com/assets/96775/12864434/c3bac13c-cc3e-11e5-9375-7fa3239fdec0.png)

![1140 before](https://cloud.githubusercontent.com/assets/96775/12864433/bc9a4f58-cc3e-11e5-86d5-f8a7a5142071.png)

**Comment by jvine** [comment]
coins look good to me.
