### ISSUE TITLE
MODS: Technical reports genre

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/stanford-mods#54]
Related to https://github.com/sul-dlss/solrmarc-sw/issues/106.

Per Hannah:

<typeOfResource>text
<genre authority="marcgt">technical report

**Comment by ndushay** [comment]
Looks like it's <mods><genre authority="marcgt">technical report</genre></mods>

See Blume:  https://sul-solr.stanford.edu/solr/mods_profiler/select?rows=0&fq=collection:blume&facet.field=genre_sim&facet.limit=-1&facet.sort=index

specific item:   https://purl.stanford.edu/bf412yb0418.mods

diff coll, not yet in SW prod:   https://purl.stanford.edu/jk084dk8092.mods

All profiled colls with tech report in genre field:

https://sul-solr.stanford.edu/solr/mods_profiler/select?rows=0&fq=genre_sim:%22technical%20report%22&facet.field=collection&facet.field=genre_sim&facet.limit=-1&facet.sort=index
