### ISSUE TITLE
1.3.3 -> 1.3.4 breaks dor-services

### ISSUE THREAD

**Issue by atz** [sul-dlss/stanford-mods#55]
Failures are around the removal/renaming of `.pub_date_sort`, similar to:
```
      Failure/Error: solr_doc['sw_pub_date_sort_ssi' ] = mods.pub_date_sort  # e.g. '0800'
      
      NoMethodError:
        undefined method `pub_date_sort' for #<Stanford::Mods::Record:0x007f828c8bc390>
      # /Users/atz/.rvm/gems/ruby-2.2.0/gems/mods-2.0.3/lib/mods/record.rb:218:in `method_missing'
      # ./lib/dor/models/describable.rb:244:in `to_solr'
      # ./spec/dor/processable_spec.rb:193:in `block (3 levels) in <top (required)>'
```

Removing a method seems like it should be related to a major version increment so that SemVer still holds.

**Comment by ndushay** [comment]
Sorry, Joe!   I probably should have made it 1.4.0, you are right.  

 I think you can just use send(:pub_date_sort) to keep it exactly the same, or call the new method I wrote, pub_year_sort_str, instead, or if you want a sortable int instead, use  pub_year_int.

**Comment by ndushay** [comment]
since we are now at version 1.4.0, I'm going to close this.  You were correct that 1.3.4  should have been 1.4.0.
