### ISSUE TITLE
MODS:  dates before 1000  should have display value with B.C. or A.D. suffix

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/stanford-mods#56]
0 < year < 1000:    add A.D. suffix

year < 0:  add B.C. suffix.

This is for a display field (as opposed to a sort field or a facet field).

Affected collections:  Walters, Roman Coins

see sul-dlss/searchworks#1140

See #53 -- would use same Solr field, and ultimately maybe end up in same stanford-mods called method but have additional methods implemented within stanford-mods code.

Where does this show up in SW?
- [x] search results  
  - [x] Solr field:   create a string display field for dates:  pub_years_ss
  - [x] stanford-mods needs method(s) to get right values
  - [x] sw-indexer-service populates Solr field 
 - [x] SearchWorks Ui code uses the new field
- [x] record view
  - [x] mods-display gem is happy for roman coins.

**Comment by LynnMcRae** [comment]
There is a metadata unit vetted specific for pre 1000 date displays in consul -- https://consul.stanford.edu/display/chimera/MODS+display+rules 

also summarized in https://jirasul.stanford.edu/jira/browse/METADOR-41, which I think has been worked on by DarrenH though I don't know why the ticket doesn't have him. It was reopened because of a backwards year shift in BD dates.

**Comment by ndushay** [comment]
per 1:1 discussions with @jvine and @jkeck , it seems we are happy with what comes from mods-display gem, so i will try to get indexing code to utilize mods-display  date parsing to populate index field, rather than recreate stuff.

**Comment by ndushay** [comment]
per further discussions, I am now working on diff code to populate new pub year display field;  it will borrow from mods_display but can't use it because  pub year comes from dateIssued as well as dateCreated,and mods_display doesn't handle dateIssued the same way.

**Comment by ndushay** [comment]
This is done for  Title[Date] part of search results.   The imprint_display field part of search results is in #52.
