### ISSUE TITLE
MODS indexing: Extent for Romain Coins

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/stanford-mods#62]
See also sul-dlss/sw-indexer-service#44

#from SW-1455

"physicalDescription > extent element (labelled Object in the collection's results view) does not appear in any of the individual records for each coin. This has to be a bug, right?? It is very important for each coin's description to include its extent, e.g. "1 coin (4.49 grams)." The donor has commented to curator about this problem, FYI. "

Example record:
https://purl.stanford.edu/xd708jk2508.mods
MODS display shows it (use https://mods-display.herokuapp.com/mods)

Need stanford-mods method to get right values

See also sul-dlss/solrmarc-sw#111

**Comment by jvine** [comment]
Okay. My current understanding is that this no longer an indexing issue at all, and I created a red herring. In Preview, when Preview existed, the Roman Coins collection displayed the extent info like this:

![screen_shot_2015-11-20_at_2 51 58_pm_480](https://cloud.githubusercontent.com/assets/6945691/12662305/5033b8c4-c5d4-11e5-8740-48f958caad24.png)

which is what we want. The only remaining issue here (other than the dates, handled separately) is how the extent is labelled on the record view, which is a MODS display issue. I'm gonna close.

**Comment by ndushay** [comment]
http://searchworks-test.stanford.edu/preview/?q=roman+coins&search_field=search&utf8=%E2%9C%93&view=list
