### ISSUE TITLE
MODS indexing:  physical location methods introduced MODS parsing bug

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/stanford-mods#71]
Or...possible bug in my understanding about how stanford-mods is supposed to work.  Perhaps somebody can enlighten me.

In 13e5f232831a14c602712b0cc1bb8a2c9f30abf1 the method `location` was added to `Stanford::Mods::Record`.  Since `location` is a top level mods element, this prevents anybody from accessing the data in that element unless the `physicalLocation` text includes Series, Accession, Folder, Box.

ModsDisplay (for one) expects that it will be able to access the top-level elements through the `Stanford::Mods::Record` class, but perhaps somebody can set me straight as to the appropriate way to do this if that should not be expected in more recent versions.

Thanks!

**Comment by ndushay** [comment]
This is a bug.  Whoops!   Will address it.  @peetucket  this may be relatively easy for you (need to rename a method, then cut a new release of stanford-mods gem,  respecting semantic versioning as fix is NOT backwards compatible)   Also, @lmcglohon  may want to comment here.

**Comment by ndushay** [comment]
So the method named location ( https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/physical_location.rb#L55 )  is currently clashing with the nom terminology from the MODS gem.   The method name needs to be changed here, then a new release of stanford-mods (respecting non-backwards compatible semantic version), and then spotlight needs to be updated to use new release and new method name.
