### ISSUE TITLE
build broken - dependencies dropped old rubies

### ISSUE THREAD

**Issue by atz** [sul-dlss/stanford-mods#82]
Re-ran the last passing build and it fails:
https://travis-ci.org/sul-dlss/stanford-mods/builds/110516055

Errors include:
`Gem::InstallError: json requires Ruby version ~> 2.0.`
`Gem::InstallError activesupport requires Ruby version >= 2.2.2.`

Need to more finely specify (SemVer or cap) dependencies or need to drop support of old versions of ruby.  Or both.

**Comment by jcoyne** [comment]
Should we add a dependency on activesupport 4.2?  I suspect it's rails 5 that's causing this trouble.

**Comment by jcoyne** [comment]
Or we can add a matrix entry for activesupport 5 + Ruby 2.3.1 and one for activesuport 4.2 and several other versions of ruby?

**Comment by atz** [comment]
yeah, i think another dimension in the matrix might be advisable.  Or maybe we can just bump major version and drop support for old rubies.

**Comment by atz** [comment]
Rails `~> 4.2` works for ruby **2.2.0**, but some of this gem's consumers are old enough to be running rails 3 on ruby **1.9.x** (FRDA is named in a `.travis.yml` file comment).

**Comment by atz** [comment]
OK, looks like FRDA has been updated to ruby 2.2, according to the puppet configs.  So I'm definitely for killing ruby 1.9 support.  Question is who else cares about ruby <2.2?  How much can we cut?

**Comment by atz** [comment]
I can build and pass tests with the rails `~> 4.2` constraint as far back as ruby **2.1.2**, so far.  I propose that we drop ruby **1.9** and **2.0**.

**Comment by atz** [comment]
#84 Solves this.
